version: "3"
services:
     nginx:
        container_name: nginx
        image: jwilder/nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /root/sendplaza/nginx.tmpl:/app/nginx.tmpl
            - /root/sendplaza/certs:/etc/nginx/certs  
        environment:
            - NETWORK_ACCESS=internal
        networks:
            - nginx-network    
        ports:
            - 80:80
            - 443:443

     fe:
         container_name: fe
         build:
           context: ./sendplaza-fe
           dockerfile: Dockerfile
           args:
              - API_URL=https://api.sendplaza.nl
         environment:
             VIRTUAL_HOST: sendplaza.nl,www.sendplaza.nl
             VIRTUAL_PORT: 80
         networks:
             - nginx-network
         links:
             - nginx
         depends_on:
             - nginx

     be:
         container_name: be
         build:
           context: ./sendplaza-be
           dockerfile: Dockerfile
         environment:
             VIRTUAL_HOST: api.sendplaza.nl
             VIRTUAL_PORT: 5000
             DATABASE_URL: postgresql://postgres:kV4DCtk2mr3hX2w25n@db:5432/sendplaza
             USER_NAME: shafiqmassir
             PASSWORD: Cb4feMGD89aMaW8W
             PORT: 5000
         networks:
             - nginx-network
         links:
             - db
             - nginx
         depends_on:
             - db
             - nginx

     db:
        container_name: db
        image: postgres:alpine
        volumes:
            - sendplazaMedia:/var/lib/postgresql/data
        networks:
            - nginx-network
        environment:
            - POSTGRES_DB=sendplaza
            - POSTGRES_PASSWORD=kV4DCtk2mr3hX2w25n

        ports:
            - 5432:5432

networks:
  nginx-network:

volumes:   
  sendplazaMedia:
