"""empty message

Revision ID: 192657719854
Revises: a6536f6a56e0
Create Date: 2021-02-03 12:25:06.849693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192657719854'
down_revision = 'a6536f6a56e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postmenapikey', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postmenapikey', 'url')
    # ### end Alembic commands ###
