"""empty message

Revision ID: 24863252a87f
Revises: 192657719854
Create Date: 2021-02-03 12:34:55.727338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24863252a87f'
down_revision = '192657719854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postmenapikey', sa.Column('api_url', sa.String(), nullable=True))
    op.drop_column('postmenapikey', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postmenapikey', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('postmenapikey', 'api_url')
    # ### end Alembic commands ###
