"""empty message

Revision ID: a6536f6a56e0
Revises: aaa70aa6eb04
Create Date: 2021-02-02 14:21:53.618053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6536f6a56e0'
down_revision = 'aaa70aa6eb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bolcreadential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('client_secret', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postmenapikey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postmenapikey')
    op.drop_table('bolcreadential')
    # ### end Alembic commands ###
